name: "RUFF"

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "*"

jobs:
  ruff:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.12]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install nose nose-exclude coverage coveralls ruff
        python -m pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
        pip install --progress-bar off .
    - name: Lint with Ruff
      run: |
        ruff check --diff surfify
