name: "TESTING"

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9, 3.12]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install nose nose-exclude coverage coveralls
        python -m pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
        pip install --progress-bar off .
    - name: Run unit tests
      run: |
        python -m unittest
    - name: Coveralls
      if: matrix.python-version == 3.9
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        coveralls --service=github
